# Generated by Django 3.2.20 on 2023-07-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='sluf',
            new_name='slug',
        ),
    ]
